ASSETS = [
    "FACEBOOK_OTC",
    "AMEX_OTC",
    "MICROSOFT_OTC",
    "TESLA_OTC",
    "APPLE_OTC",
    "BITCOIN_OTC",
    "POLYGON_OTC",
    "CHAINLINK_OTC",
    "POLKADOT_OTC",
    "CARDANO_OTC",
    "EURUSD_OTC",
    "GBPUSD_OTC",
    "USDCAD_OTC",
    "USDJPY_OTC",
    "AUDUSD_OTC"
]

EXPIRY_MINUTES = 1
MIN_PAYOUT = 0.80

MAX_SIGNALS_PER_ASSET = 3
LOOKBACK_CANDLES = 200
WICK_AGGRESSION_THRESHOLD = 0.6
